Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/09/2023
Var
base, altura, area : real


Inicio
escreva ("Insira a medida da base: ")
leia(base)
escreva ("Insira a media da altura: ")
leia(altura)

area <- base * altura

escreva ("A media da área do retângulo é: ", area, ".")
Fimalgoritmo